version: '2'
services:
  app_no_lock_1:
    image: gcc
    volumes:
      - ./app:/app
      - ./shared_file/:/shared_file/
    working_dir: /app
    command: bash ./app.sh
  app_no_lock_2:
    image: gcc
    volumes:
      - ./app:/app
      - ./shared_file/:/shared_file/
    working_dir: /app
    command: bash ./app.sh
  app_no_lock_3:
    image: gcc
    volumes:
      - ./app:/app
      - ./shared_file/:/shared_file/
    working_dir: /app
    command: bash ./app.sh
